backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Description", name: "Description", widget: "string" }
          - { label: "Author", name: "Author", widget: "string" }
          - { label: "Keywords", name: "Keywords", widget: "string" }
          - {
              label: "Hero",
              name: "hero",
              widget: "object",
              fields:
                [
                  { label: "Title Primary Text", name: "primaryText", widget: string },
                  { label: "Title Secondary Text", name: "secondaryText", widget: "text" },
                  { label: "Hero text", name: "paragraphText", widget: "text" },
                  { label: "Link 1", name: "link1", widget: "string" },
                  { label: "Button 1 text", name: "buttonText1", widget: "string" },
                  { label: "Link 2", name: "link2", widget: "string" },
                  { label: "Button 2 text", name: "buttonText2", widget: "string" }
                ],
            }
          - {
            label: "Video",
            name: "video",
            widget: "object",
            fields:
              [
                { label: "Video Link", name: "videoLink", widget: string },
              ],
          }
          - label: "Software Selection"
            name: "softwareSelection"
            widget: "object"
            fields:
              - label: "Section Title"
                name: "sectionTitle"
                widget: "object"
                fields:
                  - label: "Main Title"
                    name: "mainTitle"
                    widget: "string"
                  - label: "Sub Title"
                    name: "subTitle"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "string"
              - label: "Boxes"
                name: "boxes"
                widget: "list"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                  - label: "Alt Text"
                    name: "altText"
                    widget: "string"
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "string"
              - label: "Steps"
                name: "steps"
                widget: "list"
                fields:
                  - label: "Number"
                    name: "number"
                    widget: "number"
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Duration"
                    name: "duration"
                    widget: "string"
                    required: false
                  - label: "Content"
                    name: "content"
                    widget: "list"
                    field:
                      label: "Item"
                      name: "item"
                      widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Image Alt Text"
                name: "imageAlt"
                widget: "string"
              - label: "Second Title Section"
                name: "secondTitleSection"
                widget: "object"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Small Range Image"
                    name: "smallRangeImage"
                    widget: "image"
                  - label: "Small Range Image Alt Text"
                    name: "smallRangeImageAlt"
                    widget: "string"
                  - label: "Images"
                    name: "images"
                    widget: "object"
                    fields:
                      - label: "Solution Diagram Image"
                        name: "solutionDiagramImage"
                        widget: "image"
                      - label: "Solution Diagram Image Alt Text"
                        name: "solutionDiagramImageAlt"
                        widget: "string"
              - label: "Approach Build"
                name: "approachBuild"
                widget: "object"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Icons"
                    name: "icons"
                    widget: "list"
                    fields:
                      - label: "Icon Image"
                        name: "src"
                        widget: "image"
                      - label: "Icon Alt Text"
                        name: "alt"
                        widget: "string"
                      - label: "Icon Title"
                        name: "title"
                        widget: "string"
                      - label: "Icon Description"
                        name: "description"
                        widget: "string"
          - label: "Timeline Section"
            name: "timelineSection"
            widget: "list"
            fields: [
               { label: "Reverse", name: "reverse", widget: "boolean" }
               { label: "Small Text", name: "smallText", widget: "string" }
               { label: "Heading", name: "heading", widget: "string" }
               { label: "List", name: "list", widget: "list", allow_add: true, fields: [ { label: "Item", name: "item", widget: "string" } ] }
               { label: "Image", name: "image", widget: "string" }
               { label: "Alt Text", name: "alt", widget: "string" }
               { label: "Number", name: "number", widget: "number" }
            ]
          - label: "Approach Section"
            name: "approachSection"
            widget: "object"
            fields:
              - label: "Section Title"
                name: "sectionTitle"
                widget: "string"
              - label: "Section Subtitle"
                name: "sectionSubtitle"
                widget: "string"
              - label: "Boxes"
                name: "boxes"
                widget: "list"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "string"
                  - label: "Text"
                    name: "text"
                    widget: "string"
          - label: "Pricing Section"
            name: "pricingSection"
            widget: "object"
            fields:
              - label: "Section Title"
                name: "sectionTitle"
                widget: "string"
              - label: "Pricing Boxes"
                name: "pricingBoxes"
                widget: "list"
                fields:
                  - label: "Pricing Box Title"
                    name: "title"
                    widget: "string"
                  - label: "Pricing Box Color"
                    name: "color"
                    widget: "string"
                  - label: "Pricing Box Items"
                    name: "items"
                    widget: "list"
                    fields:
                      - label: "Item"
                        name: "item"
                        widget: "string"
                      - label: "Additional Text"
                        name: "additionalText"
                        widget: "string"
                      - label: "Button Text"
                        name: "buttonText"
                        widget: "string"
                      - label: "Button Icon"
                        name: "buttonIcon"
                        widget: "string"
                      - label: "Plan Details"
                        name: "planDetails"
                        widget: "string"
                      - label: "Plan Includes"
                        name: "planIncludes"
                        widget: "list"
                        field:
                          label: "Include Item"
                          name: "includeItem"
                          widget: "string"
          - label: "For Who Section"
            name: "forWhoSection"
            widget: "object"
            fields:
              - label: "Section Title"
                name: "sectionTitle"
                widget: "string"
              - label: "Columns"
                name: "columns"
                widget: "list"
                fields:
                  - label: "Column Icon"
                    name: "icon"
                    widget: "string"
                  - label: "Column Title"
                    name: "title"
                    widget: "string"
                  - label: "Column Description"
                    name: "description"
                    widget: "text"
          - label: "Customer Reviews Section"
            name: "customerReviewsSection"
            widget: "object"
            fields:
              - label: "Section Title"
                name: "sectionTitle"
                widget: "string"
              - label: "Reviews"
                name: "reviews"
                widget: "list"
                fields:
                  - label: "Review Text"
                    name: "text"
                    widget: "text"
                  - label: "Customer Name"
                    name: "name"
                    widget: "string"
                  - label: "Customer Position"
                    name: "position"
                    widget: "string"
          - label: "FAQ Section"
            name: "faqSection"
            widget: "object"
            fields:
              - label: "Section Title"
                name: "sectionTitle"
                widget: "string"
              - label: "Accordion 1"
                name: "accordion1"
                widget: "list"
                fields:
                  - label: "Question"
                    name: "question"
                    widget: "string"
                  - label: "Answer"
                    name: "answer"
                    widget: "text"
              - label: "Accordion 2"
                name: "accordion2"
                widget: "list"
                fields:
                  - label: "Question"
                    name: "question"
                    widget: "string"
                  - label: "Answer"
                    name: "answer"
                    widget: "text"
          - label: "Contact Section"
            name: "contactSection"
            widget: "object"
            fields:
              - label: "Section Title"
                name: "sectionTitle"
                widget: "string"
              - label: "Button Text"
                name: "buttonText"
                widget: "string"
              - label: "Button Icon"
                name: "buttonIcon"
                widget: "string"
              - label: "Button Link"
                name: "buttonLink"
                widget: "string"

